### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by psycho67**
main muf

### CODE REVIEW

**Comment by theshurka** [comment]
привет

**Comment by bebra2022** [comment]
bebraa

**Comment by rt777111** [comment]
fuck

**Comment by theshurka** [comment]
привет лохи

**Comment by youricpmommy** [comment]
хуй

**Comment by youricpmommy** [comment]
[Programming - Midterm (AM).pdf](https://github.com/theshurka/shurka/files/8035257/Programming.-.Midterm.AM.pdf)
#

**Comment by youricpmommy** [comment]
[Programming - Midterm (PM).pdf](https://github.com/theshurka/shurka/files/8035266/Programming.-.Midterm.PM.pdf)

**Comment by bebra2022** [comment]
https://howtodoinjava.com/java/puzzles/fizzbuzz-solution-java/#:~:text=FizzBuzz%20is%20a%20fun%20game,you%20say%20the%20next%20number.&text=If%20the%20number%20is%20a,the%20game%20continues%20without%20you.

**Comment by rt777111** [comment]
sucka blyat suka blyat

**Comment by bebra2022** [comment]
👋 Hi, I’m @bebra2022

**Comment by bebra2022** [comment]
import java.util.Scanner;
import java.util.Random;

public class Main {
    public static void main(String[] args) {
        // declare variables
        int computer, user;
        // declare an array to store the moves name
        String move[] = {"Rock", "Paper", "Scissor"};

        // create an object of Random class   
        Random random = new Random();
        // create an object of Scanner class
        Scanner sc = new Scanner(System.in);

        // keep repeating until user wants to exit
        while (true) {
            // Display the choices
            System.out.println("Enter 1 for Rock.");
            System.out.println("Enter 2 for Paper.");
            System.out.println("Enter 3 for Scissor.");
            System.out.println("Enter 0 to exit.");
            System.out.print("Choice >> ");
            // take input from user
            user = sc.nextInt();

            // check if player wants to exit
            if (user == 0)
                break;

            // input validation
            if (!(user >= 1 && user <= 3)) {
                System.out.println("\nEnter a valid choice!\n");
                continue;
            }

            // computer chooses random move
            // Generate a random number from 1 to 3
            // Number 1, 2, 3 indicate rock, 
            // paper, scissor resepectively
            computer = random.nextInt(3) + 1;

            // display the move of each player
            // fetch move name from string array
            System.out.print("\nYou played     : " + move[user - 1]);
            System.out.print("\nComputer played: " + move[computer - 1]);

            //check for the winner
            // rock vs paper => paper wins
            // rock vs scissor => rock wins
            // paper vs scissor => scissor wins
            if (computer == user)
                System.out.println("\nIt is a tie!");
            else if (computer == 1 && user == 3)
                System.out.println("\nComputer wins!");
            else if (computer == 2 && user == 1)
                System.out.println("\nComputer wins!");
            else if (computer == 3 && user == 2)
                System.out.println("\nComputer wins!");
            else
                System.out.println("\nYou win!");

            // new line
            System.out.println("");

        }
    }
}

**Comment by generalvgorode** [comment]
na baze

**Comment by An1onio** [comment]
jjjj

**Comment by bebra2022** [comment]
_Corrected version_



import java.util.Scanner;
import java.util.Random;

public class Main {
    public static void main(String[] args) {
        int computer, user;        
        
        String move[] = {"Rock", "Paper", "Scissor"};

          
        Random random = new Random();
        
        Scanner sc = new Scanner(System.in);

        
        while (true) {
            
            System.out.println("Enter 1 for Rock.");
            System.out.println("Enter 2 for Paper.");
            System.out.println("Enter 3 for Scissor.");
            System.out.println("Enter 0 to exit.");
            System.out.print("Choice >> ");
            
            user = sc.nextInt();

            
            if (user == 0)
                break;

            
            if (!(user >= 1 && user <= 3)) {
                System.out.println("\nEnter a valid choice!\n");
                continue;
            }

            
            computer = random.nextInt(3) + 1;

            
            System.out.print("\nYou played     : " + move[user - 1]);
            System.out.print("\nComputer played: " + move[computer - 1]);

           
            if (computer == user)
                System.out.println("\nIt is a tie!");
            else if (computer == 1 && user == 3)
                System.out.println("\nComputer wins!");
            else if (computer == 2 && user == 1)
                System.out.println("\nComputer wins!");
            else if (computer == 3 && user == 2)
                System.out.println("\nComputer wins!");
            else
                System.out.println("\nYou win!");

            
            System.out.println("");

        }
    }
}

**Comment by psycho67** [comment]
import java.util.Scanner;
import java.util.Random;

public class Main {
public static void main(String[] args) {
int computer, user;

    String move[] = {"Rock", "Paper", "Scissor"};

      
    Random random = new Random();
    
    Scanner sc = new Scanner(System.in);

    
    while (true) {
        
        System.out.println("Enter 1 for Rock.");
        System.out.println("Enter 2 for Paper.");
        System.out.println("Enter 3 for Scissor.");
        System.out.println("Enter 0 to exit.");
        System.out.print("Choice >> ");
        
        user = sc.nextInt();

        
        if (user == 0)
            break;

        
        if (!(user >= 1 && user <= 3)) {
            System.out.println("\nEnter a valid choice!\n");
            continue;
        }

        
        computer = random.nextInt(3) + 1;

        
        System.out.print("\nYou played     : " + move[user - 1]);
        System.out.print("\nComputer played: " + move[computer - 1]);

       
        if (computer == user)
            System.out.println("\nIt is a tie!");
        else if (computer == 1 && user == 3)
            System.out.println("\nComputer wins!");
        else if (computer == 2 && user == 1)
            System.out.println("\nComputer wins!");
        else if (computer == 3 && user == 2)
            System.out.println("\nComputer wins!");
        else
            System.out.println("\nYou win!");

        
        System.out.println("");

    }
}
}

**Comment by rt777111** [comment]
import java .util.Scanner;

class Main {
  public static void main(String[] args) {
    Scanner input = new Scanner(System.in);
    
    String name = input.nextLine();
    String name2 = input.nextLine();
if (name == name2){
  System.out.println("Strings are equal");
}
else  {
  System.out.println("Strings are not equal");
}
  }
}

**Comment by glebsheesh** [comment]
.

**Comment by youricpmommy** [comment]
самое время

**Comment by An1onio** [comment]
все, я тут

**Comment by Kekiroki2020** [comment]
go

**Comment by generalvgorode** [comment]
connection check

**Comment by Kekiroki2020** [comment]
connection is on

**Comment by rt777111** [comment]
suka blyat suka blyat

**Comment by generalvgorode** [comment]
hajimeeeeeeeeeeeeee

**Comment by generalvgorode** [comment]
kto takoy glebsheeesh??

**Comment by youricpmommy** [comment]
пизда нам

**Comment by bebra2022** [comment]
+++

**Comment by youricpmommy** [comment]
что такое программирование

**Comment by An1onio** [comment]
пишите если что

**Comment by An1onio** [comment]
👨‍💼

**Comment by psycho67** [comment]
public class Exercise3 {
    /*
      Write a program that receives numbers as program arguments and prints to console if numbers are even or odd
      You might compile and run the program via command line or by editing configuration and pass program arguments
    */
    public static void main(String[] args) {
        checkingIfEvenOrOdd(0);
        checkingIfEvenOrOdd(1);
        checkingIfEvenOrOdd(2);
        checkingIfEvenOrOdd(7);
        checkingIfEvenOrOdd(24);
    }

    public static void checkingIfEvenOrOdd(int number) {
        if (number %2 == 0) {
            System.out.println(number + " is an even number");
        }
        else {
            System.out.println(number + " is an odd number");
        }
    }
}

**Comment by psycho67** [comment]
вероятно это будет

**Comment by youricpmommy** [comment]
пиздец какой-то

**Comment by bebra2022** [comment]
r u sure?

**Comment by bebra2022** [comment]
assignment 1 // even or odd 20 points
 The modulo operation (%) returns the remainder of a division, after one number is divided by another (called the modulus of the operation). For example, 5 % 2 would result in 1, since 5 divided by 2 has a quotient of 2 and a remainder of 1, and 9 % 3 would result in 0, since 9 divided by 3 is 3 with no remainder.
Write a program that checks if a number (that the user inputs) is even or odd. A number is even when it is divisible by 2 and odd when it is not. So for example, if the user puts in the number 5, the program should print the following into the console:
5 is odd.

**Comment by bebra2022** [comment]
for antonio

**Comment by generalvgorode** [comment]
nu kak tam

**Comment by theshurka** [comment]
ну что?

**Comment by psycho67** [comment]
class Main {
  public static void CheckingIfEvenOrOdd (int number) {
    if (number %2 == 0) {
    System.out.println (number + "is an even number");
    }
    else {
      System.out.println ("is an odd number");
    }
    }
  }

**Comment by psycho67** [comment]
нужен сканнер

**Comment by An1onio** [comment]
в инете не нашёл

**Comment by psycho67** [comment]
class Main {
  public static void main(String[] args){
CheckingIfEvenOrOdd(5);
  }
  public static void CheckingIfEvenOrOdd (int number) {
    if (number %2 == 0) {
    System.out.println (number + "is an even number");
    }
    else {
      System.out.println (number + "is an odd number");
    }
    }
  }

**Comment by youricpmommy** [comment]
выглядит сложно 
они точно чет поймут

**Comment by youricpmommy** [comment]
хотя хз

**Comment by psycho67** [comment]
наоборот

**Comment by youricpmommy** [comment]
не не, я не туда посмотрела просто

**Comment by psycho67** [comment]
только немного измените

**Comment by psycho67** [comment]
чтоб не палиться

**Comment by psycho67** [comment]
Write a program that takes a word (that the user inputs) and prints the amount of vowels (a, e, i, o, u) and the amount of
consonants (the other letters in the alphabet) in the word to the console.
Hint: remember that checking for equality is case sensitive (“a” and “A” are different characters). So think of a way to
solve this. So, if the user puts in the word “Chocolate”, the program should print the following into the console

**Comment by psycho67** [comment]
Antonio

**Comment by generalvgorode** [comment]
import java.util.Scanner;

class Main {
public static void Checkingnumber(){
  System.out.println("write a number");
  Scanner dan = new Scanner(System.in);
  int number = input.nextLine();
  
if (number %2 == 0) {
System.out.println (number + " is an even number");
}
else {
System.out.println ("is an odd number");
}
}
}

в чем ошибка,

**Comment by generalvgorode** [comment]
???

**Comment by An1onio** [comment]
это для психа

// Java program to count vowels in a string

public class GFG {

        

    // Function to check the Vowel

    static boolean isVowel(char ch)

    {

        ch = Character.toUpperCase(ch);

        return (ch=='A' || ch=='E' || ch=='I' ||

                           ch=='O' || ch=='U');

    }

      

    // Returns count of vowels in str

    static int countVowels(String str)

    {

        int count = 0;

        for (int i = 0; i < str.length(); i++)

            if (isVowel(str.charAt(i))) // Check for vowel

                ++count;

        return count;

    }

      

    // Driver code

    public static void main(String args[])

    {

        //string object

        String str = "abc de";

      

        // Total numbers of Vowel

        System.out.println(countVowels(str));

    }
}
// This code is contributed by Sumit Ghosh

**Comment by An1onio** [comment]
все, пишите вопросы

**Comment by An1onio** [comment]
import java.util.Scanner;

class Main {
public static void Checkingnumber(){
System.out.println("write a number");
Scanner dan = new Scanner(System.in);
int number = input.nextLine();

if (number %2 == 0) {
System.out.println (number + " is an even number");
}
else {
System.out.println ("is an odd number");
}
}
}


проверь, все ли ты скобки правлильно закрыл

**Comment by psycho67** [comment]
public class CountVowelConsonant {    
    public static void main(String[] args) {    
            
        //Counter variable to store the count of vowels and consonant    
        int vCount = 0, cCount = 0;    
            
        //Declare a string    
        String str = "This is a really simple sentence";    
            
        //Converting entire string to lower case to reduce the comparisons    
        str = str.toLowerCase();    
            
        for(int i = 0; i < str.length(); i++) {    
            //Checks whether a character is a vowel    
            if(str.charAt(i) == 'a' || str.charAt(i) == 'e' || str.charAt(i) == 'i' || str.charAt(i) == 'o' || str.charAt(i) == 'u') {    
                //Increments the vowel counter    
                vCount++;    
            }    
            //Checks whether a character is a consonant    
            else if(str.charAt(i) >= 'a' && str.charAt(i)<='z') {      
                //Increments the consonant counter    
                cCount++;    
            }    
        }    
        System.out.println("Number of vowels: " + vCount);    
        System.out.println("Number of consonants: " + cCount);    
    }    
}

**Comment by theshurka** [comment]
оно работает?

**Comment by bebra2022** [comment]
yep

**Comment by An1onio** [comment]
саня, что-то нужно?

**Comment by youricpmommy** [comment]
хочу мак

**Comment by youricpmommy** [comment]
пойдемте покушаем потом а

**Comment by psycho67** [comment]
кто тут лучший?

**Comment by psycho67** [comment]
с вас обед в маке

**Comment by generalvgorode** [comment]
бля второе не работает

**Comment by generalvgorode** [comment]
pamagite

**Comment by youricpmommy** [comment]
я вообще не понимаю, кто из вас кто

**Comment by bebra2022** [comment]
import java.util.Scanner;

public class Main {  
    public static void main(String[] args) { 
     Scanner scannerInput = new Scanner(System.in); 
          
        int vCount = 0, cCount = 0;  
          
        System.out.println("Write something down: ");

        String lmao = scannerInput.nextLine();

        lmao = lmao.toLowerCase();  
          
        for(int i = 0; i < lmao.length(); i++) {  
              
         if(lmao.charAt(i) == 'a' || lmao.charAt(i) == 'e' || lmao.charAt(i) == 'i' || lmao.charAt(i) == 'o' || lmao.charAt(i) == 'u') {  
           
           vCount++; 

            }  
            else if(lmao.charAt(i) >= 'a' && lmao.charAt(i)<='z') {    
               cCount++;  
            }  
        }  
        System.out.println("Number of vowels: " + vCount);  

        System.out.println("Number of consonants: " + cCount);  
    }  
}

**Comment by bebra2022** [comment]
попробуй
только поменяй lmao на другое

**Comment by bebra2022** [comment]
rabotaet?

**Comment by bebra2022** [comment]
@generalvgorode

**Comment by generalvgorode** [comment]
spasibo bolshoye!!! vse pomenyal

**Comment by psycho67** [comment]
вова

**Comment by psycho67** [comment]
где ошибки?

**Pull request closed without merging**
